export const TemplateEvents = {
    START_GAME: "START_GAME",
    FINISH_GAME: "FINISH_GAME",

    START_BOX_FLYING: "START_BOX_FLYING",
    FINISH_BOX_FLYING: "FINISH_BOX_FLYING",
    COLLIDE_BOX: "COLLIDE_BOX",

    CLICK_RESTART_BUTTON: "CLICK_RESTART_BUTTON",
    CLICK_AUTOPLAY_BUTTON: "CLICK_AUTOPLAY_BUTTON"
};