export const SoundActionType = {
    PLAY_SOUND: "PLAY_SOUND",
    STOP_SOUND: "STOP_SOUND",
    CHANGE_SOUND_VOLUME: "CHANGE_SOUND_VOLUME",
    CHANGE_GLOBAL_VOLUME: "CHANGE_GLOBAL_VOLUME",
    FADE_SOUND: "FADE_SOUND"
};